from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent

MODELS_JAR_DIR_NAME = "saved_models"
PREPROCESSED_DATA_JAR_DIR_NAME = "preprocessed_data"
INFERENCE_OUTPUTS_JAR_DIR_NAME = "inferrence_outputs"

MODELS_JAR_PATH = PROJECT_ROOT / MODELS_JAR_DIR_NAME
PREPROCESSED_DATA_JAR_PATH = PROJECT_ROOT / PREPROCESSED_DATA_JAR_DIR_NAME
INFERENCE_OUTPUTS_PATH = PROJECT_ROOT / INFERENCE_OUTPUTS_JAR_DIR_NAME